//
//  GM Food.swift
//  LearnByLearning
//
//  Created by Lauriane Mollier on 20/03/2017.
//  Copyright © 2017 Lauriane Mollier. All rights reserved.
//

import Foundation


let Raven_and_the_First_People: TraductedText = TraductedText(
    originalText: Text(lang: Lang.en,
                       title: "Raven and the First People",
                       text: "Raven was bored. He was walking along the beach in Haida Gwaii, looking for some new way to amuse himself. As he walked along the beach, the blue ocean in front of him and the green forest behind him didn’t seem interesting. Raven wanted to play, but there was no one to play with.\n\nThen he heard a strange sound, unlike any sound he knew. He looked up and down the beach. Where was it coming from? As he walked he noticed a large white clamshell lying in the sand. Inside the clamshell were tiny creatures, unlike any he had seen before.\n\nRaven bent down to get a closer look. The creatures seemed afraid of him, so he began to coax them in a gentle voice, “Come out. Come out. Don’t be afraid. I won’t hurt you.”\n\nA few of the creatures came out of the clamshell. They were very different from Raven. They had no feathers, no wings, and no beaks. Like him, they walked on two legs, but they had arms, faces with mouths, and black hair. They spoke to each other in a language that Raven didn’t understand. These tiny creatures were the first humans.\n\nRaven enjoyed watching these humans play and explore the world. After a while, when he was beginning to feel bored again, he noticed that these humans were only women. There were no men. Raven had an idea. He wondered if he could find some men. He searched for a long time. Then he saw some shells. He opened one of the shell and found some lovely, tiny men. He brought the men to the women.\n\nRaven enjoyed watching the behaviour of the women and men. He saw them begin to pair off and have children. The human families moved to other parts of the island. Since that day, many generations of humans have grown and flourished, and Raven has never been bored."),
    traductedText: [
        Text(lang: Lang.es,
             title: "Raven y las Primeras Personas",
             text: "Raven estaba aburrido. Caminaba por la playa de Haida Gwaii, buscando alguna nueva manera de divertirse. Mientras caminaba por la playa, el océano azul delante de él y el bosque verde detrás de él no parecían interesantes. Raven quería jugar, pero no había nadie con quien jugar.\n\nEntonces escuchó un sonido extraño, diferente a cualquier sonido que conociera. Miró arriba y abajo por la playa. ¿De dónde venía? Mientras caminaba notó una gran concha blanca de almeja que estaba en la arena. En el interior de la concha había pequeñas criaturas, muy diferentes a las que había visto antes.\n\nRaven se agachó para verlas más de cerca. Las criaturas parecían temerle, así que comenzó a convencerles con una voz suave: “Salid. Salid. No tengáis miedo. No os haré daño.“\n\nAlgunas de las criaturas salieron de la concha. Eran muy diferentes a Raven. No tenían plumas, ni alas, ni picos. Como él, caminaban sobre dos piernas, pero tenían brazos, rostros con bocas y pelo negro. Se hablaban entre ellos en un lenguaje que Raven no entendía. Estas pequeñas criaturas fueron los primeros humanos.\n\nRaven disfrutó viendo a estos humanos jugar y explorar el mundo. Después de un tiempo, cuando empezaba a sentirse aburrido de nuevo, notó que estos humanos eran sólo mujeres. No había hombres. Raven tuvo una idea. Se preguntó si podría encontrar a algunos hombres. Buscó durante mucho tiempo. Entonces vio algunas almejas. Abrió una de las conchas y encontró unos hombres preciosos y diminutos. Llevó a los hombres a las mujeres.\n\nA Raven le gustaba ver el comportamiento de las mujeres y los hombres. Él los vio empezar a emparejarse y a tener hijos. Las familias humanas se trasladaron a otras partes de la isla. Desde ese día, muchas generaciones de humanos han crecido y florecido, y Raven nunca jamás se aburrió."),
        Text(lang: Lang.de,
             title: "Raven und die ersten Menschen",
             text: "Raven war langweilig. Er ging am Strand in Haida Gwaii und suchte eine neue Art und Weise, um sich zu amüsieren. Während er den Strand entlangging war der blaue Ozean vor ihm und der grüne Wald hinter ihm nicht interessant genug. Raven wollte spielen, aber da war niemand zum Spielen.\n\nDann hörte er ein seltsames Geräusch, anders als jedes andere Geräusch, dass er kannte. Er sah den Strand auf und ab. Woher kommt es? Als er den Strand entlangging, bemerkte er eine große weiße Muschel, die im Sand lag. Im Inneren der Muschel waren winzige Kreaturen, anders als alle, die er bisher gesehen hatte.\n\nRaven bückte sich, um einen genaueren Blick werfen zu können. Die Kreaturen schienen vor ihm Angst zu haben, also fing er an, sie mit einer sanften Stimme zu locken: “Kommt heraus. Kommt heraus. Fürchtet euch nicht, ich werde euch nicht verletzen.“\n\nEin paar der Kreaturen kamen aus der Muschel hervor. Sie waren ganz anders als Raven. Sie hatten keine Federn, keine Flügel und keine Schnäbel. Wie er, gingen sie auf zwei Beinen, aber sie hatten Arme, Gesichter mit Mund und schwarzen Haaren. Sie sprachen miteinander in einer Sprache, die Raven nicht verstand. Diese kleinen Kreaturen waren die ersten Menschen.\n\nRaven hat es genossen, diese Menschen spielen zu sehen und wie sie die Welt erkunden. Nach einer Weile, als er sich wieder langweilte, bemerkte er, dass diese Menschen nur Frauen waren. Es waren keine Männer vorhanden. Raven hatte eine Idee. Er fragte sich, ob er einige Männer finden könnte. Er suchte lange. Dann sah er ein paar Muscheln. Er öffnete eine der Muscheln und fand schöne, winzige Männer. Er brachte die Männer zu den Frauen.\n\nRaven genoss das Verhalten der Frauen und Männer. Er sah, dass sie anfingen sich paarweise anzuordnen und Kinder zu bekommen. Die menschlichen Familien zogen in andere Teile der Insel. Seit diesem Tag an sind viele Generationen von Menschen herangewachsen und Raven hat sich nie wieder gelangweilt."),
        Text(lang: Lang.fr,
             title: "Raven et les premières personnes",
             text: "Raven s'ennuyait. Il était en train de marcher le long de la plage à Haida Gwaii, cherchant une nouvelle façon de s'amuser. Comme il marchait le long de la plage, le bleu de l'océan en face de lui et le vert de la forêt, derrière lui, ne semblait pas intéressant. Raven voulait jouer, mais il n'y avait personne avec qui jouer.\n\nPuis il entendit un bruit étrange, contrairement à tous les sons qu'il connaissait. Il regarda en haut et en bas de la plage. D'où venait-il? Pendant qu'il marchait, il remarqua une grande coquille blanche allongée dans le sable. A l'intérieur de la coquille il y avait des créatures minuscules, contrairement à celles qu'il avait vues avant.\n\nRaven se pencha pour regarder de plus près. Les créatures semblaient avoir peur de lui, alors il a commencé à les amadouer d'une voix douce: “Sortez. Sortez. N'ayez pas peur. Je ne vais pas vous faire de mal.”\n\nQuelques-unes des créatures sont sorties de la coquille. Ils étaient très différents de Raven. Ils n'avaient pas de plumes, pas d'ailes et pas de becs. Comme lui, ils marchent sur deux jambes, mais ils avaient des bras, des visages avec des bouches et des cheveux noirs. Ils parlaient entre eux dans une langue que Raven ne comprenais pas. Ces petites créatures étaient les premiers humains.\n\nRaven aimait regarder ces humains jouer et explorer le monde. Après un certain temps, quand il commençait à s'ennuyer encore, il remarqua que ces humains étaient uniquement des femmes. Il n'y avait pas d'hommes. Raven avait une idée. Il s'est demandé s'il pouvait trouver certains hommes. Il a cherché pendant longtemps. Puis il a vu des coquilles. Il a ouvert la coquille et a trouvé des hommes adorables et minuscules. Il a amené les hommes aux femmes.\n\nRaven aimait regarder le comportement des femmes et des hommes. Il les vit commencer à s’accoupler  et avoir des enfants. Les familles humaines ont déménagé dans d'autres parties de l'île. Depuis ce jour, plusieurs générations d'êtres humains ont grandi et prospéré, et Raven ne s’est jamais plus ennuyé."),
        Text(lang: Lang.ru,
             title: "Ворон и Первые Люди",
             text: "Ворону было скучно. Он ходил вдоль пляжа в Хайда Гваии в поиске какого-нибудь нового пути для  развлечения.  Пока он ходил вдоль пляжа, ни синий океан перед ним, ни зелёный лес позади него, не казались интересными. Ворон хотел играть, но там не было некого с кем играть.\n\nНо тогда он услышал странный звук, не похожий ни на один из которых он знал. Он посмотрел вверх и в низ по пляжу. Откуда он шёл? Когда он ходил, он обратил внимание на белую раковину моллюска, которая лежала на песке. Внутри раковины моллюска находились крошечные существа, не похожие ни на какие из тех что он видел раньше.\n\nВорон наклонился, чтобы увидеть поближе. Было похоже что существа его боялись, поэтому он начал уговаривать их с нежным голосом, “Выходите. Выходите. Не бойтесь. Я вам не причиню вреда.“\n\nНесколько существ вышло из раковины. Они очень отличались от Ворона. У них не было перьев, ни крыл, ни клювов. Как и он, они ходили на двух ногах, но имели руки, лица с ртами, и чёрные волосы. Они разговаривали друг с другом на языке который Ворон не понимал. Эти первые существа являлись первыми людьми.\n\nВорон наслаждался смотря как эти люди играют и исследуют мир. Спустя некоторое время, когда ему снова начинало быть скучно, он обратил внимание на то, что эти луди были только женщинами. Там не было мужчин. У ворона возникла идея. Он задался вопросом если мог найти кое-каких мужчин. Он долго искал. И тогда, он увидел несколько ракушек. Он открыл одну из ракушек, и нашёл несколько крошечных, милых мужчин. Он принёс мужчин женщинам.\n\nВорон наслаждался смотря на поведение женщин и мужчин. Он увидел как они начали соединяться и иметь детей. Семьи людей переместились на другие краи острова. С того дня, множество поколений людей выросло и процвело, а Ворону уже никогда не было скучно."),
        ],
    voc: VovRaven_and_the_First_People().voc, level: Level.B1, author: "Mary Mahoney", titleAudio: "Raven_and_the_First_People")



class VovRaven_and_the_First_People{
    
    var voc: [(key: OriginalWord, value: [Word])] = []
    
    init(){
        
    }
}




