//
//  Мы и налоги.swift
//  LearnByLearning
//
//  Created by Lauriane Mollier on 05/04/2017.
//  Copyright © 2017 Lauriane Mollier. All rights reserved.
//

import Foundation

let MyINalogi: TraductedText = TraductedText(
    originalText: Text(lang: Lang.ru,
                       title: "Мы и налоги",
                       text: "    Ещё сравнительно недавно мы о налогах и знать ничего не знали. Вычитают там в бухгалтерии какие-то копейки, ну и пусть себе вычитают. Неприятно, конечно, но терпеть можно. Сейчас ситуация коренным образом изменилась. Мы с искренним удивлением, узнали что налоги (причём немалые) нужно платить самим. Это нас более всего и напрягает. В голове не умещается,  что от нас требуют, чтобы мы сами пришли в налоговую инспекцию и сами на самих же себя настучали. Ну ладно бы на соседа или сослуживца. Но на самого себя!.. Это же уму непостижимо. О таких интимных подробностях у нас даже жена (или муж) не знает. А тут сам приходишь и совершенно посторонним людям говоришь, сколько ты заработал. Да у тебя денег-то этих давно нет. Уже не помнишь, куда их подевал. И, здрасьте пожалуйста, приходи плати с них налоги. За кого они нас держат, не понимаю.\n\n    А чтобы, видимо, с налогами легче было расставаться, нас странным образом успокаивают: мол, заплатите, и будете спать спокойно. Во-первых, мы и так спим как убитые, а во-вторых, вот как раз если мы их заплатим, то уж тогда точно не уснём. Это же надо такое придумать! Мы же не в какой-нибудь Америке живём. И не в Европе какой-нибудь. Конечно, немного и в Европе, но немного и в Азии. А потом у нас самобытный путь, вековые традиции. Нет, налоги у нас не приживутся. Точно. Оброк, подать, всё что угодно, только не налоги. Пришлите сборщиков, вооружённых, введите иго какое-нибудь, организуйте лёгкую оккупацию… Немного посопротивляемся и заплатим. А так… самим чтобы… Странно это как-то, непривычно. Давайте лучше договоримся: пусть наверху воруют, а мы не будем платить налоги. А? Или пусть каждый сообщает о доходах другого. Или… В общем нужно ещё подумать.\n\n\nПо Геннадию Попову\n\n“Литературная газета”, www.lgz.ru - № 42, 11-17/10/06"),
    traductedText: [
        Text(lang: Lang.en,
             title: "We and taxes",
             text: "    Until recently we didn’t know a thing a bout taxes. They deduce some pennies in the accounts department; let them count. It’s unpleasant, of course, but it’s durable. Nowadays the situation changed dramatically. To our genuine surprise we discovered that we must pay the taxes (and considerable ones) by ourselves. This is what bothers us most of all. They require us to come to the tax office and to rat ourselves out, it’s beyond belief.  It’s okay if we did it to a neighbour or to a co-worker. But to ourselves! … It blows my mind.  Not even our wives (or husbands) know this kind of intimate details. And there you go by yourself, and you tell how much you have earned to some complete strangers.  By the way, you don’t even have that money anymore. You don’t even remember where you spend it. Then come, pay it’s taxes. How about that! I can’t understand who are they taking us for.\n\n    They are calming us down in a strange way, apparently to make it easier for us to let the taxes go: pay up, they say, and you will sleep peacefully. In the first place, we already sleep as a dead person and in the second place, if we precisely pay up, then we are not going to be able to sleep for sure. Oh the things they come up with! We don’t live in some kind of America. Neither we live in some kind of Asia. Even though, we do live a little bit in Europe, and a little bit in Asia, too. But then we have our own ways, ancient traditions. No, taxes are not going to take root here. For sure. Tribute, duty, anything you like, but not taxes. Send us collectors, armed people, embed some kind of yoke, organise a light occupation… We will fight back a little bit and then we will pay. But as it is… To do that ourselves… It’s somewhat strange , unusual. Let’s better reach an agreement: let people up there steal and we will not have to pay our taxes. Ok? Or let everyone to report one another’s income. Or… All in all, we still have to think about it."),
        Text(lang: Lang.es,
             title: "Nosotros y los impuestos",
             text: "    Hasta hace relativamente poco no sabíamos nada acerca de impuestos. En el departamento de contabilidad deducen algunos centavos, pues déjales que deduzcan. No es agradable, claro, pero se puede soportar. Ahora la situación ha cambiado radicalmente. Hemos descubierto, para nuestra verdadera sorpresa, que tenemos que pagar los impuestos (y considerables) nosotros mismos. Esto es lo que más nos molesta. No nos cabe en la cabeza que nos exijan que vayamos nosotros mismos a la Agencia Tributaria y nos delatemos, también,  a nosotros mismos. Vale que se lo hagas a un vecino o a un compañero de trabajo. Pero a uno mismo?...Es que es inconcebible. Ni siquiera nuestra esposa (o esposo) conocen esos detalles tan íntimos. Y aquí llegas y cuentas cuánto dinero has ganado a personas totalmente desconocidas. Encima, ese dinero hace mucho que ni lo tienes.  Ya ni te acuerdas de dónde lo metiste. Y ahora ve a pagar impuestos de ese dinero. Qué te parece! No entiendo por quién nos toman.\n\n    Y , por lo visto, para que sea más fácil separarse de los impuestos, nos calman de una manera extraña: paguen y dormirán tranquilos, dicen.  En primer lugar, ya y así dormimos como muertos, y en segundo lugar, precisamente si los pagamos, seguro que no podremos dormir. Qué cosas inventan! No vivimos en algún tipo de América, oiga. Ni en algún tipo de Europa. Aunque, un poco en Europa y un poco en Asia, también. Luego, tenemos una manera de hacer las cosas propia, tradiciones centenarias. No, los impuestos no se van a arraigar aquí. Sí, claro. Tributo, carga fiscal, lo que deseen, pero no impuestos. Envíen cobradores, a gente armada, introduzcan algún yugo, organicen una ocupación ligera… Resistiremos un poco y pagaremos. Pero así...Hacerlo nosotros mismos… Es un poco raro, inusual. Mejor vamos a pactar: dejemos que los de arriba roben y nosotros no pagaremos impuestos. Vale? O que cada uno informe sobre los ingresos del otro. O… En general, todavía hay que pensarlo."),
        Text(lang: Lang.de,
             title: "Wir und die Steuern",
             text: "    Vor vergleichsweise nicht all zu langer Zeit haben wir von Steuern keine Ahnung gehabt. Da rechnet die Buchhaltung irgendwelche Kopeken heraus. Nun gut, soll sie doch herausrechnen. Es war natürlich unangenehm, aber auszuhalten. Heutzutage hat sich die Situation im Kern verändert. Zu unserem aufrichtigen Erstaunen stellten wir fest, dass wir die (nebenbei ziemlich hohen) Steuern selbst zahlen müssen. Das belastet uns am meisten. Es passt nicht in den Kopf, dass von uns gefordert wird, selbst zur Steueraufsicht zu gehen und uns selbst zu verpfeifen. Es wäre ja in Ordnung, wenn es der Nachbar oder der Arbeitskollege wäre. Aber sich selbst!.. Das ist doch unbegreiflich. Über solche intimen Details weiß bei uns nicht mal die eigene Frau (oder Mann) Bescheid. Hier gehst du aber selbst zu völlig fremden Menschen und sagst, wie viel du verdient hast. Außerdem hast du dieses Geld doch lange nicht mehr. Kannst dich nicht erinnern, wo du es gelassen hast. Und, Hallöchen, komm und zahl davon die Steuern. Für wen sie uns halten, verstehe ich nicht.\n\n    Und damit wir uns anscheinend  leichter von den Steuern trennen können, werden wir auf eine merkwürdige Weise beruhigt: Bezahlen Sie und schlafen Sie ruhig. Erstens, wir schlafen auch so schon wie tot, und zweitens, gerade erst, wenn wir sie bezahlt haben, schlafen wir sicherlich nicht ein. Wer denkt sich so etwas aus! Wir leben doch hier nicht in irgendeinem Amerika. Und nicht in irgendeinem Europa. Natürlich ein bisschen in Europa, aber auch ein wenig in Asien. Außerdem bestreiten wir unseren eigenen Weg und haben jahrhundertealte Traditionen.  Nein, die Steuern werden sich bei uns nicht einleben. Ganz sicher. Zwangsabgabe, Bede, alles Mögliche nur nicht die Steuern. Schicken Sie Vollstrecker, Militärs, führen Sie irgendein Joch ein, organisieren Sie eine leichte Okkupation... Wir wehren uns ein bisschen und werden dann zahlen. Und hier... selbst hin... Es ist irgendwie merkwürdig, ungewohnt. Lassen Sie uns lieber ein Abkommen schließen: Sollen die da oben stehlen und wir werden keine Steuern zahlen. Und? Oder, dass jeder über das Einkommen des Anderen berichtet.  Oder... Allgemein muss man darüber noch nachdenken."),
        Text(lang: Lang.fr,
             title: "Les impôts et nous",
             text: "    Il n’y a encore pas si longtemps, nous ne connaissions rien des impôts. Ils nous prélèvent quelques kopecks de notre compte, eh bien qu’on les laisse prélever. C’est désagréable, bien sûr, mais supportable. Maintenant, la situation a radicalement changé. Nous sommes vraiment surpris car nous avons appris que nous devions nous-mêmes payer des impôts (qui sont élevés). Pour nous, c’est ça le plus ennuyeux. C’est inconcevable que l’on nous demande de nous présenter à l’Inspection fiscale et de nous dénoncer nous-même. Encore, si c’était un voisin ou un collègue. Mais moi ! … C’est quand même ahurissant. Même ma femme (ou moi, son mari), nous ne connaissons pas tous ces détails intimes. Et là, des personnes tout à fait inconnues arrivent et me demandent combien j’ai gagné. Oui, vous n’avez plus d’argent depuis longtemps. Vous ne vous souvenez plus où vous les avez mis. S’il vous plait, venez avec nous pour payer vos taxes. Pour qui nous prennent-ils, je ne comprends pas.\n\n    Apparemment, il est plus facile de payer nos impôts séparément. Ils nous rassurent d’une façon étrange : ils nous disent « payez et vous dormirez plus tranquillement ». Premièrement, nous dormons comme des morts et, deuxièmement, si nous leur payons les taxes, ce n’est certainement pas pour dormir. Je n’arrive même pas à y imaginer ! Nous ne vivons pas quelque part en Amérique. Et ni quelque part en Europe. Bien sûr, un petit peu et en Europe et en Asie. Et ensuite, nous avons parcouru un chemin original de traditions séculaires. Non, on ne s’habitue pas aux impôts. Exactement. Une redevance, un tribut, tout ce que vous voulez, sauf des impôts. Envoyez des percepteurs, des hommes armés, établissez un joug, organisez une petite occupation… Nous résisterons un peu et nous paierons. Et alors… de nous-même… C’est bizarre, c’est anormal. Allez, négocions mieux : laissez-les voler de l’argent, nous ne paieront pas d’impôt. Hum… Ou laissons tout le monde dire ce que les autres gagnent. Ou… En bref, il faut encore y réfléchir.")
        ],
    voc: [
        OriginalWord(lang: Lang.es , wordInText: "", neutralWord: "") : [Word(lang: Lang.en, neutralWord: ""), Word(lang: Lang.de, neutralWord: "")]
    ], level: Level.A2, author: "Геннадий Попов", titleAudio: "MyINalogi")
